name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: my-app/package-lock.json
          
      - name: Install dependencies
        working-directory: ./my-app
        run: npm ci
        
      - name: Build application
        working-directory: ./my-app
        run: npm run build
        
      - name: Run Lighthouse CI
        working-directory: ./my-app
        run: npx lhci autorun
        continue-on-error: true
        
      - name: Check if Lighthouse files exist
        run: |
          echo "Checking for Lighthouse files..."
          if [ -d "my-app/.lighthouseci" ]; then
            echo "✅ .lighthouseci directory exists"
            ls -la my-app/.lighthouseci/
          else
            echo "❌ .lighthouseci directory does not exist"
            echo "Contents of my-app directory:"
            ls -la my-app/
          fi
        
      - name: Copy Lighthouse files to root
        if: always()
        run: |
          echo "Copying Lighthouse files to root directory..."
          cp -r my-app/.lighthouseci ./lighthouse-results
          echo "Files copied to lighthouse-results directory:"
          ls -la lighthouse-results/
          
      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: lighthouse-results/
          retention-days: 30
