name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: my-app/package-lock.json
          
      - name: Install dependencies
        working-directory: ./my-app
        run: npm ci
        
      - name: Build application
        working-directory: ./my-app
        run: npm run build
        
      - name: Run Lighthouse CI
        working-directory: ./my-app
        run: npx lhci autorun
        continue-on-error: true
        
      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: my-app/.lighthouseci/
          retention-days: 30
